### ISSUE TITLE
Error at "defaultSettings" in config.js

### ISSUE THREAD

**Issue by Quinnzy** [TheMonDon/Mythical-Bot#189]
![Screenshot_2024_0207_084954](https://github.com/TheMonDon/Mythical-Bot/assets/142702497/c0e479e8-3e5d-436a-8d61-94533345038a)

**Comment by TheMonDon** [comment]
Adding a comma after youtubeCookie should solve this

**Comment by Quinnzy** [comment]
> Adding a comma after youtubeCookie should solve this

Oh thanks 🙏 im new to javascript so i dont know its that simple
